version: "3"
services: 
  lumos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghanatava/lumos
    depends_on: 
      - postgres
    container_name: lumos-backend
    ports:
      - "8000:8000"
    env_file: 
      - .env

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - lumos_data:/var/lib/postgresql/data

volumes:
  lumos_data:
